# Generated by Django 3.2.4 on 2024-05-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='checked_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
