# Generated by Django 3.2.4 on 2024-06-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_link_checked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='checked_at',
        ),
    ]
