services:
  postgresql:
    image: postgres:16
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: python_project_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgresql: { }

networks:
  backend: { }